version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install  # If you have any dependencies (e.g., package.json)
  build:
    commands:
      - echo Building the app...
      - # Any build steps, if needed, like compiling assets or minifying files
  post_build:
    commands:
      - echo Build complete. Starting deployment...
      - aws s3 cp ./ s3://ci-cd-packages/ --recursive  # Upload everything from the current directory to the S3 bucket

artifacts:
  files:
    - '**/*'  # This ensures all files in the directory are included as artifacts
  discard-paths: yes
