version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the app...
      - npm run build
  post_build:
    commands:
      - echo Build complete. Starting deployment...
      - aws s3 cp /path/to/build/output s3://your-bucket-name --recursive
artifacts:
  files:
    - '**/*'
  discard-paths: yes
