version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo No build step required for HTML files.
  post_build:
    commands:
      - echo Build complete. Starting deployment...
      - cd /home/ec2-user/hisaad-html
      - aws s3 cp --recursive . s3://ci-cd-packages/

artifacts:
  files:
    - '**/*'
  discard-paths: No
