version: 0.2

phases:
  install:
    commands:
      - echo No dependencies to install.
  build:
    commands:
      - echo No build step required. Proceeding with deployment...
  post_build:
    commands:
      - echo Build complete. Starting deployment...
      - aws s3 cp ./ s3://ci-cd-packages/ --recursive  # Upload everything from the current directory to the S3 bucket

artifacts:
  files:
    - '**/*'  # This ensures all files in the directory are included as artifacts
  discard-paths: yes
