version: 0.2

phases:
  install:
    commands:
      # Install dependencies or tools if needed
      echo Installing dependencies...
      sudo yum install -y openssh-clients

  build:
    commands:
      # Download the RPM from S3
      echo Downloading RPM from S3...
      aws s3 cp s3://ci-cd-packages/openssh-clients-8.7p1-8.amzn2023.0.13.x86_64.rpm /tmp/

      # Install the RPM package
      echo Installing the RPM package...
      sudo yum install -y /tmp/openssh-clients-8.7p1-8.amzn2023.0.13.x86_64.rpm

  post_build:
    commands:
      # Verify if the RPM was installed successfully
      echo Verifying the installation...
      rpm -qa | grep openssh

artifacts:
  files:
    - '**/*'
